export default {

NAVBAR_SELECTED: 'NAVBAR_SELECTED',
TOPRATED_SELECTED: 'TOPRATED_SELECTED',
FRAG_CREATED: 'FRAG_CREATED',
FETCH_FRAGS: 'FETCH_FRAGS',
PROFILE_CREATED: 'PROFILE_CREATED',
USER_LOGGED_IN: 'USER_LOGGED_IN',
RATE_FRAG: 'RATE_FRAG',
UPDATE_FRAG: 'UPDATE_FRAG',
PROFILES_RECEIVED: 'PROFILES_RECEIVED',
FETCH_TOP_ACE: 'FETCH_TOP_ACE',
FETCH_ALL_FRAGS: 'FETCH_ALL_FRAGS',
PROFILE_MY_FRAGS: 'PROFILE_MY_FRAGS',
UPDATE_PROFILE: 'UPDATE_PROFILE',
FETCH_PROFILE_AND_FRAGS: 'FETCH_PROFILE_AND_FRAGS',
TUTORIAL_CREATED: 'TUTORIAL_CREATED',
FETCH_TUTORIAL: 'FETCH_TUTORIAL',
FETCH_MAPS: 'FETCH_MAPS'



}
